choco install -y ^
    7zip ^
    audacity ^
    audacity-lame ^
    blender ^
    bzeditor ^
    cpu-z ^
    cygwin ^
    deepl ^
    discord ^
    epicgameslauncher ^
    everything ^
    ffmpeg ^
    firefox ^
    flac ^
    foobar2000 ^
    gimp ^
    git ^
    googlechrome ^
    googledrive ^
    gpu-z ^
    hwinfo ^
    hwmonitor ^
    keepassxc ^
    lavfilters ^
    microsoft-windows-terminal ^
    mpc-hc ^
    obs-studio ^
    origin ^
    owncloud-client ^
    pandoc ^
    powertoys ^
    procmon ^
    qbittorrent ^
    rufus ^
    slack ^
    spotify ^
    steam ^
    sublimetext3 ^
    thunderbird ^
    twitch ^
    vcxsrv ^
    virtualbox ^
    visualstudio2019community ^
    vscode ^
    wget ^
    winaero-tweaker ^
    winscp ^
    wireshark ^
    wsl2 ^
    wsltty^
    youtube-dl"